### ISSUE TITLE
Does `finkel-mode` exist?

### ISSUE THREAD

**Issue by 0atman** [finkel-lang/finkel#3]
There are no references to it, apart from

```
To use the finkel-mode, first clone the source repository:
$ git clone https://repository/of/finkel-mode.git
```

Which seem like a placeholder?

**Comment by 8c6794b6** [comment]
Indeed, it's a placeholder, thank you for pointing out. 

Will push the repository and update the document.

**Comment by 8c6794b6** [comment]
Made a [finkel-mode][finkel-mode] repository and update the document, closing this issue.

[finkel-mode]: https://github.com/finkel-lang/finkel-mode
