### ISSUE TITLE
Would a clojure-style thread macro (->) be possible?

### ISSUE THREAD

**Issue by 0atman** [finkel-lang/finkel#4]
This guy: https://clojure.org/guides/threading_macros

Which allows rewriting

```clojure
(string (first (range 0 10)))
```

as

```clojure
(-> (range 0 10)
  first
  string)
```

(both psudeocode)

**Comment by 8c6794b6** [comment]
I suppose, it's trivially done with function since functions in Finkel are lazy:

```clojure
;;; File: cljthr.fnk

(defmodule Main
  (import (Data.Function (&))))

(defn (:: main (IO ()))
  (do
    ;; Fully parenthesized
    (print (show (head (enumFromTo 0 10))))

    ;; Same as above, but with operator expansion with `$'
    ($ print show head (enumFromTo 0 10))

    ;; Same again, but with operator expansion with `&'.
    (& (enumFromTo 0 10) head show print)

    ;; Making partially aplied function in Haskell and Finkel is easy,
    ;; mimicing following clojure expression which uses `->>' macro:
    ;;
    ;;   (->> (range 10)
    ;;        (filter odd?)
    ;;        (map #(* % %))
    ;;        (reduce +))
    ;;
    (print (& [0 .. 10]
              (filter odd)
              (map (flip ^ 2))
              (foldr1 +)))))
```

Running above:

```console
$ finkel make cljthr.fnk
[1 of 1] Compiling Main             ( cljthr.fnk, cljthr.o )
Linking cljthr ...
$ ./cljthr
"0"
"0"
"0"
165
```

Perhaps [operator application][opapp] section in the documentation may help how ``$`` and ``&`` are treated.

@0atman Does above show what you were looking for?

[opapp]: https://finkel.readthedocs.io/en/latest/contents/language-syntax.html#operator-applications

**Comment by 0atman** [comment]
You're a MAGICIAN! The & form is EXACTLY what I need. Thank you so much!

I wanted to get this working in haskell, but I see Finkel has what I need! (https://stackoverflow.com/q/60464090/333294)
